#+TITLE: Learning Django
About 8 months ago I decided to learn Python. I hacked around a little on some different "lern 2 code" tutorials. The best way to learn is by doing so I'm learning Python now by learning Django. 

I've been blogging and creating sites in WordPress and other platforms since the early 2000s (b2/b2 evolution era). The direction the WordPress core is heading these days is fine but I feel like I'm fighting it more than creating with it. That I have to have a separate plugin to keep the editor from mangling my markup is frustrating. The Gutenberg editor made me want to scream. This is all my own problem and isn't a judgement on the WP Developers. What am I writing this in? Spacemacs. That should tell you something...

Eventually I'll try [[http://mezzanine.jupo.org/][Mezzanine]] but for now I'd like to keep this as vanilla as possible. 

This project is using:

- Django 2.1.2
- jQuery 3.3.1
- FontAwesome 5.3.1
- Bootstrap 4.1.3

* Resources
I've used each of these for different things. Nothing has been a 1 stop resource but that's the way it should be. At this point I'm trying not to get into tutorial purgatory. I'm actively working on this app and learning. I still /really/ struggle with Javascript.  
+ [[https://djangogirls.com][Django Girls]] where it all began...it's a wonderful starting point but I struggled so much following the tutorial online. I think it needs to be updated or...I don't know what. Definitely worth contributing to or supporting. (free)
+ [[https://www.youtube.com/playlist?list=PL-osiE80TeTtoQCKZ03TU5fNfx2UY6U4p][Corey Schafer's Django/Python Tutorial series]] (free)
+ [[https://docs.djangoproject.com/][The /Excellent/ Django Documentation]] (free)
+ [[https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django][Mozilla Django/Python Guide]] (free)
+ [[https://www.udemy.com/python-and-django-full-stack-web-developer-bootcamp/][Python and Django Full Stack Web Developer Bootcamp]] (paid) Note: This entire course is Python 3 and Django 1.11. I've since udpated to Django 2.1.2 and have all but abandoned this one. If you're legit a beginner and need some css/html/js/jquery foundations, this is excellent.
+ [[https://www.youtube.com/channel/UCAx4nmhI7S1RcPiaG-Uw0tg][Max Goodridge's Python for Beginners and Django Framework series]] (free)
